#! /usr/bin/env bash

#### Copy all output to log file.
log=install.$$.log
echo "Recording log in $log ..."
exec > >(tee $log) # Requires fdescfs mounted to /dev/fd on FreeBSD.
exec 2>&1

cd /opt
git clone https://github.com/mariobarbareschi/Bellerophon
cd Bellerophon
mkdir build
cd build
## add fix paradiseo
cmake ../ -DCMAKE_MODULE_PATH=/opt/ParadisEO-2.0/cmake/module/
make -j4
make install
