#! /usr/bin/env bash

#### Copy all output to log file.
log=install.$$.log
echo "Recording log in $log ..."
exec > >(tee $log) # Requires fdescfs mounted to /dev/fd on FreeBSD.
exec 2>&1

cd /opt
#download paradiseo
wget https://gforge.inria.fr/frs/download.php/31732/ParadisEO-2.0.1.tar.gz
tar xvfz ParadisEO-2.0.1.tar.gz
rm ParadisEO-2.0.1.tar.gz
cd ParadisEO-2.0
mkdir build
cd build
cmake ..
make -j4
make install
