#! /usr/bin/env bash

#### Copy all output to log file.
log=install.$$.log
echo "Recording log in $log ..."
exec > >(tee $log) # Requires fdescfs mounted to /dev/fd on FreeBSD.
exec 2>&1

cd /opt
git https://github.com/mariobarbareschi/clang-chimera
cd clang-chimera
mkdir build
cd build
cmake ../
make -j4
make install
