#!/bin/bash

for i in {8..23};
do
  top_entity=fpmult_8_$i
  source_file=${top_entity}.vhd
  tcl_projfile=${top_entity}.tcl

  ./run_flopoco useHardMult=no pipeline=yes frequency=400 name=$top_entity FPMult we=8 wf=$i;
  sudo chown $(whoami) flopoco.vhdl
  sudo chgrp $(whoami) flopoco.vhdl
  mv -f flopoco.vhdl ${source_file}

  cp project_template.tcl $tcl_projfile 
  sed "s/_TOP_LEVEL_ENTITY_/${top_entity}/g" -i $tcl_projfile
done

for i in {8..23};
do
  top_entity=fpadd_8_$i
  source_file=${top_entity}.vhd
  tcl_projfile=${top_entity}.tcl

  ./run_flopoco useHardMult=no pipeline=yes frequency=400 name=$top_entity FPAdd we=8 wf=$i;
  sudo chown $(whoami) flopoco.vhdl
  sudo chgrp $(whoami) flopoco.vhdl
  mv -f flopoco.vhdl ${source_file}

  cp project_template.tcl $tcl_projfile 
  sed "s/_TOP_LEVEL_ENTITY_/${top_entity}/g" -i $tcl_projfile
done
