#!/bin/bash

usage() { 
        echo "Usage: $0 -x /xilinx_vivado_bin"; 
        exit 1; 
}

while getopts "x:" o; do
    case "${o}" in
        x)
            xilinx_vivado=${OPTARG}
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if [ -z "${xilinx_vivado}" ]; then
    usage
fi

xilinx_vivado=$(realpath $xilinx_vivado)
echo $xilinx_vivado

for i in {8..23};
do
  top_entity=fpmult_8_$i
  tcl_projfile=${top_entity}.tcl

  rm -rf $top_entity
	${xilinx_vivado}/vivado -mode batch -nojournal -nolog -notrace -source $tcl_projfile;
done

for i in {8..23};
do
  top_entity=fpadd_8_$i
  tcl_projfile=${top_entity}.tcl

  rm -rf $top_entity
	${xilinx_vivado}/vivado -mode batch -nojournal -nolog -notrace -source $tcl_projfile;
done
