// N2D2 auto-generated file.
// @ Mon Sep 16 12:44:48 2019

#ifndef N2D2_EXPORTC_ENV_LAYER_H
#define N2D2_EXPORTC_ENV_LAYER_H

#define ENV_SIZE_X 32
#define ENV_SIZE_Y 32
#define ENV_NB_OUTPUTS 1

#define ENV_DATA_UNSIGNED 1

#define ENV_OUTPUTS_SIZE (ENV_NB_OUTPUTS*ENV_SIZE_X*ENV_SIZE_Y)
#define ENV_BUFFER_SIZE (ENV_OUTPUTS_SIZE)

#define OUTPUTS_HEIGHT 1
#define OUTPUTS_WIDTH 1
#define OUTPUTS_SIZE (OUTPUTS_WIDTH*OUTPUTS_HEIGHT)
#define NB_OUTPUTS 10
#define NB_TARGETS 10

#endif // N2D2_EXPORTC_ENV_LAYER_H
