// N2D2 auto-generated file.
// @ Mon Sep 16 12:44:48 2019

#ifndef N2D2_EXPORTC_POOL2_LAYER_H
#define N2D2_EXPORTC_POOL2_LAYER_H

#include "typedefs.h"
#define POOL2_NB_OUTPUTS 16
#define POOL2_NB_CHANNELS 16
#define POOL2_OUTPUTS_WIDTH 5
#define POOL2_OUTPUTS_HEIGHT 5
#define POOL2_CHANNELS_WIDTH 10
#define POOL2_CHANNELS_HEIGHT 10
#define POOL2_POOL_WIDTH 2
#define POOL2_POOL_HEIGHT 2
#define POOL2_PADDING_X 0
#define POOL2_PADDING_Y 0
#define POOL2_STRIDE_X 2
#define POOL2_STRIDE_Y 2
#define POOL2_POOLING Max

#define POOL2_ACTIVATION Linear
#define POOL2_SHIFT 0
#endif // N2D2_EXPORTC_POOL2_LAYER_H
