#!/bin/bash

cd ~
#Download ParadisEO
wget https://gforge.inria.fr/frs/download.php/31732/ParadisEO-2.0.1.tar.gz
tar xvfz ParadisEO-2.0.1.tar.gz > /dev/null
rm -f ParadisEO-2.0.1.tar.gz

cd ~/ParadisEO-2.0
mkdir build
cd ~/ParadisEO-2.0/build

#Solve FindDoxygen CMake Policy Requirements
sed -i "s/CMAKE_MINIMUM_REQUIRED(VERSION 2.6)/CMAKE_MINIMUM_REQUIRED(VERSION 3.3)/g" ../eo/CMakeLists.txt

cmake ..
make -j4 2> /dev/null
make install

