#!/bin/bash

#Clone Clang-Chimera repo
cd ~
git clone https://github.com/andreaaletto/clang-chimera.git

#Prepare Clang-Chimera for building
cd ~/clang-chimera
mkdir build
cd ~/clang-chimera/build

#Insert LLVM components into the CMakeLists.txt of clang-chimera
LLVM_LIBS="$(llvm-config --components)"
sed -i "s/insert-llvm-libs-here/${LLVM_LIBS}/g" ~/clang-chimera/CMakeLists.txt
sed -i "s/all-targets //g" ~/clang-chimera/CMakeLists.txt

#Solve LLVM 3.9.1 bug of jit cmake
sed -i 's/list(APPEND link_components "jit")/list(APPEND link_components "mcjit")/g' /usr/lib/cmake/llvm/LLVM-Config.cmake

cmake ..
make -j4  2> /dev/null
make install
