#!/bin/bash

echo "Downloading LLVM/Clang source. This will take a while..."

cd ~
git clone https://github.com/llvm-mirror/llvm.git llvm
cd llvm
git checkout release_39

cd tools
git clone https://github.com/llvm-mirror/clang.git clang
cd clang
git checkout release_39

echo "LLVM/Clang download completed."

cd ~/llvm
mkdir build
cd build

CC=gcc CXX=g++ cmake -DLLVM_ENABLE_CXX1Y=true -DLLVM_ENABLE_RTTI=ON -DLLVM_TARGET_ARCH="X86" -DLLVM_TARGETS_TO_BUILD="X86" -DLLVM_ENABLE_FFI=ON -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -G Ninja ..

ninja 2> /dev/null
ninja install
