#!/bin/bash
echo "Installing dependencies..."
apt-get -qq install -y git libssl-dev libomp-dev ninja-build build-essential zlib1g-dev libffi-dev libedit-dev libncurses5-dev libboost-dev doxygen tar python wget graphviz vim nano lcov gdb > /dev/null
