#!/bin/bash

echo "Downloading LLVM/Clang source. This will take a while..."

cd ~
svn co -q http://llvm.org/svn/llvm-project/llvm/tags/RELEASE_391/final llvm

cd ~/llvm/tools
svn co -q http://llvm.org/svn/llvm-project/cfe/tags/RELEASE_391/final clang

cd ~/llvm/tools/clang/tools
svn co -q http://llvm.org/svn/llvm-project/clang-tools-extra/tags/RELEASE_391/final extra

echo "LLVM/Clang download completed."

cd ~/llvm
mkdir build
cd build

CC=gcc CXX=g++ cmake -DLLVM_ENABLE_CXX1Y=true -DLLVM_ENABLE_RTTI=ON -DLLVM_TARGET_ARCH="X86" -DLLVM_TARGETS_TO_BUILD="X86" -DLLVM_ENABLE_FFI=ON -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -G Ninja ..

ninja 2> /dev/null
ninja install
