// N2D2 auto-generated file.
// @ Mon Sep 16 12:33:02 2019

#ifndef N2D2_EXPORTC_POOL1_LAYER_H
#define N2D2_EXPORTC_POOL1_LAYER_H

#include "typedefs.h"
#define POOL1_NB_OUTPUTS 6
#define POOL1_NB_CHANNELS 6
#define POOL1_OUTPUTS_WIDTH 14
#define POOL1_OUTPUTS_HEIGHT 14
#define POOL1_CHANNELS_WIDTH 28
#define POOL1_CHANNELS_HEIGHT 28
#define POOL1_POOL_WIDTH 2
#define POOL1_POOL_HEIGHT 2
#define POOL1_PADDING_X 0
#define POOL1_PADDING_Y 0
#define POOL1_STRIDE_X 2
#define POOL1_STRIDE_Y 2
#define POOL1_POOLING Max
#define POOL1_OUTPUT_OFFSET 0
#define POOL1_ACTIVATION Linear
#define POOL1_SHIFT 0


#endif // N2D2_EXPORTC_POOL1_LAYER_H
